name: Build aapt2

on:
  push:
    branches:
      - main
    paths-ignore:
      - get_sources.sh
      - README.md
      - .github/**
      - patches/*
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Reason'     
        required: false
        default: 'Update package'

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target_abi: [arm64-v8a, armeabi-v7a, x86_64, x86]
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'false'

      - name: Prerequisites
        run: |
            sudo apt install \
            ninja-build \
            autogen \
            autoconf \
            libtool \
            build-essential \
            curl \
            -y

      - name: Download tools
        run: |
            cleaner=termux-elf-cleaner
            cleaner_version=v2.1.1
            cleaner_url=https://github.com/termux/termux-elf-cleaner/releases/download/${cleaner_version}/${cleaner}
            curl -L $cleaner_url > $cleaner
            chmod +x $cleaner
        
      - uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r25b
          add-to-path: false
      - run: bash build.sh ${{ matrix.target_abi }}
        env:
          CLEAN: ./termux-elf-cleaner
          NDK: ${{ steps.setup-ndk.outputs.ndk-path }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: aapt2-${{ matrix.target_abi }}
          path: output/${{ matrix.target_abi }}
